import {clientPresets} from './products.js';
import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {createShell,L} from './shell.js';
import {presets,furnitureMesh} from './furniture.js';
const $=id=>document.getElementById(id), host=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#f0f1ee');
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch(e){$('loading').textContent='3D 화면을 열 수 없습니다. WebGL을 지원하는 브라우저로 열어주세요.';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.VSMShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(40,1,.05,150), controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=1;controls.maxDistance=55;
let walkMode=false,walkYaw=0,walkPitch=0,lookTouch=null;const walkKeys=new Set(),walkClock=new THREE.Clock(),walkRay=new THREE.Raycaster();
scene.add(new THREE.HemisphereLight(0xffffff,0xbcb9b0,1.9));const sun=new THREE.DirectionalLight(0xfff8ef,2.3);sun.position.set(-10,24,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-16,right:16,top:16,bottom:-16});sun.shadow.bias=-.00015;sun.shadow.normalBias=.015;sun.shadow.radius=4;sun.shadow.blurSamples=8;scene.add(sun);
const X=x=>x,Z=z=>z;
const {walls,glasses,frames,doors,roomData,inside}=createShell(scene);
const glassLabel=document.createElement('label');glassLabel.innerHTML='<input type="checkbox" id="glassToggle" checked>외부 창 표시';document.querySelector('.tools').prepend(glassLabel);$('glassToggle').onchange=e=>{for(const m of [...glasses,...frames])m.visible=e.target.checked;$('status').textContent=e.target.checked?'외부 통창과 창틀을 다시 표시했어요.':'외부 통창과 창틀을 모두 숨겼어요.'};
const labels=roomData.map(([t,x,y])=>{const el=document.createElement('div');el.className='roomlabel';el.textContent=t;$('labels').appendChild(el);return {el,p:new THREE.Vector3(X(x),.12,Z(y))}});
let full=false;function heightMode(){for(const m of walls){m.scale.y=full?2.6/.75:1;m.position.y=(full?2.6:.75)/2}for(const m of glasses){m.scale.y=full?1:.65/2.5;m.position.y=(full?2.5:.65)/2}for(const m of frames){if(m.geometry.parameters.height>1){m.scale.y=full?1:.7/2.6;m.position.y=(full?2.6:.7)/2}else m.position.y=full?2.55:.7}for(const d of doors){d.scale.y=full?1:.72/2.1;d.position.y=(full?2.1:.72)/2}}
$('fullwalls').onchange=e=>{full=e.target.checked;heightMode()};heightMode();$('labelsToggle').onchange=e=>$('labels').hidden=!e.target.checked;
function view(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='plan'){camera.position.set(0,Math.max(32,29/camera.aspect),.001);controls.target.set(0,0,0)}else if(v==='living'){camera.position.set(-14,14,12);controls.target.set(-6,0,-1)}else if(v==='reverse'){camera.position.set(-17,17,-15);controls.target.set(-3,0,0)}else if(v==='rooms'){camera.position.set(13,12,11);controls.target.set(4.8,0,2.2)}else if(v==='roomsReverse'){camera.position.set(-3,12,-10);controls.target.set(4.8,0,2.2)}else if(v==='eye'){camera.position.set(L(2,8)[0],1.6,L(2,8)[1]);controls.target.set(L(2,2)[0],1.5,L(2,2)[1]);full=true;$('fullwalls').checked=true;heightMode()}else{camera.position.set(0,Math.max(23,25/camera.aspect),Math.max(16,17/camera.aspect));controls.target.set(0,0,0)}controls.update()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(walkMode)stopWalk();view(b.dataset.view)});$('reset').onclick=()=>{if(walkMode)stopWalk();view('overview')};
const viewbar=document.querySelector('.viewbar'),walkButton=document.createElement('button');walkButton.id='walkMode';walkButton.textContent='🚶 워크스루';walkButton.title='실제 눈높이에서 WASD 또는 방향키로 이동';viewbar.append(walkButton);const crosshair=document.createElement('div');crosshair.id='crosshair';crosshair.textContent='＋';crosshair.hidden=true;host.append(crosshair);const walkPad=document.createElement('div');walkPad.id='walkPad';walkPad.hidden=true;walkPad.innerHTML='<button data-walk="ArrowUp">▲</button><button data-walk="ArrowLeft">◀</button><button data-walk="ArrowDown">▼</button><button data-walk="ArrowRight">▶</button><small>화면을 밀어 둘러보기</small>';host.append(walkPad);
function lookForward(){camera.rotation.order='YXZ';camera.rotation.y=walkYaw;camera.rotation.x=walkPitch}
function startWalk(){select(null);walkMode=true;document.body.classList.add('walking');full=true;$('fullwalls').checked=true;heightMode();const a=L(2,8),b=L(2,2);camera.position.set(a[0],1.65,a[1]);const dx=b[0]-a[0],dz=b[1]-a[1];walkYaw=Math.atan2(-dx,-dz);walkPitch=0;lookForward();controls.enabled=false;walkButton.classList.add('active');crosshair.hidden=false;walkPad.hidden=false;$('labels').hidden=true;$('status').textContent='워크스루: WASD·방향키 이동, 마우스/드래그로 둘러보기, Esc로 종료';if(matchMedia('(pointer:fine)').matches)renderer.domElement.requestPointerLock?.()}
function stopWalk(){walkMode=false;document.body.classList.remove('walking');walkKeys.clear();lookTouch=null;controls.enabled=true;walkButton.classList.remove('active');crosshair.hidden=true;walkPad.hidden=true;$('labels').hidden=!$('labelsToggle').checked;if(document.pointerLockElement===renderer.domElement)document.exitPointerLock?.()}
walkButton.onclick=()=>walkMode?stopWalk():startWalk();document.addEventListener('pointerlockchange',()=>{if(walkMode&&matchMedia('(pointer:fine)').matches&&document.pointerLockElement!==renderer.domElement)stopWalk()});document.addEventListener('mousemove',e=>{if(!walkMode||document.pointerLockElement!==renderer.domElement)return;walkYaw-=e.movementX*.0025;walkPitch=Math.max(-1.35,Math.min(1.35,walkPitch-e.movementY*.0025));lookForward()});document.addEventListener('keydown',e=>{if(walkMode&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight'].includes(e.code)){walkKeys.add(e.code);e.preventDefault()}});document.addEventListener('keyup',e=>walkKeys.delete(e.code));walkPad.querySelectorAll('button').forEach(b=>{const code=b.dataset.walk;b.onpointerdown=e=>{walkKeys.add(code);b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>walkKeys.delete(code)});
const furniture=[];let selected=null,selectionBox=null;
const catalogGroups={
  '보유 가구':['standard','slabTable','modularSofa','pkLounge','ropeBar','naturalRug','woodChair','softStool','casala','woodArm','blockCoffee','easeStand','sornayDesk'],
  '조명 · 오디오':['woodLamp','vacantLamp','tripodLamp','paperPendant','akariXP1','basicaMinima','akari26N','monitorSpeaker','speakerStand','goldmund'],
  '업무 공간':['steelcaseLeap','dell27']
};
for(const [label,types] of Object.entries(catalogGroups)){const section=document.createElement('section');section.className='productGroup';const title=document.createElement('h3');title.textContent=label;const grid=document.createElement('div');grid.className='productGrid';for(const type of types){const p=clientPresets[type];if(!p)continue;const b=document.createElement('button');b.dataset.add=type;b.textContent=p.name;grid.append(b)}section.append(title,grid);$('clientCatalog').append(section)}
for(const [type,p] of Object.entries(clientPresets)){const opt=document.createElement('option');opt.value=type;opt.textContent=p.name;$('replaceProduct').append(opt)}
const basicCatalog=document.querySelector('.basicCatalog');for(const type of ['humanStand','humanSit','humanLie']){const b=document.createElement('button');b.dataset.add=type;b.textContent=presets[type].name;basicCatalog.prepend(b)}
$('replaceProduct').onchange=e=>{if(!selected||!e.target.value)return;const type=e.target.value;const pos={x:selected.x,z:selected.z,r:selected.r,lift:selected.lift||0};delete selected.photo;Object.assign(selected,clientPresets[type],pos,{type});rebuild(selected);select(selected);e.target.value='';$('status').textContent='위치와 각도를 유지하고 제품·치수를 교체했어요.'};

function disposeItem(o){if(!o.mesh)return;scene.remove(o.mesh);const materials=new Set();o.mesh.traverse(m=>{if(m.isMesh){m.geometry.dispose();(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>materials.add(x))}});materials.forEach(m=>{if(!m.map?.userData.shared)m.map?.dispose();m.dispose()});}
function rebuild(o){disposeItem(o);o.mesh=furnitureMesh(o);scene.add(o.mesh);if(o===selected)showSelection()}
function showSelection(){if(selectionBox){scene.remove(selectionBox);selectionBox.dispose();selectionBox=null}if(selected){selectionBox=new THREE.BoxHelper(selected.mesh,0x536c66);scene.add(selectionBox)}}
function select(o){selected=o;$('editor').hidden=!o;if(o){$('colorEditor').hidden=!!clientPresets[o.type]||o.type==='photo'||o.type==='tv';$('fcolor').value='#'+new THREE.Color(o.color).getHexString();$('productPhoto').hidden=true;$('productNote').textContent=o.note||'';$('selectedName').textContent=o.name;$('fw').value=o.w;$('fd').value=o.d;$('fh').value=o.h;$('lift').value=o.lift||0;$('furnitureName').value=o.name;syncAngle()}showSelection();renderList()}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.add,o={...presets[type],type,x:L(2.5,5)[0],z:L(2.5,5)[1],r:0};furniture.push(o);rebuild(o);select(o);$('editor').scrollIntoView({block:'nearest',behavior:'smooth'})});
for(const [id,key] of [['fw','w'],['fd','d'],['fh','h']])$(id).onchange=e=>{if(!selected)return;const n=Number(e.target.value);if(!Number.isFinite(n)||n<Number(e.target.min)||n>Number(e.target.max)){e.target.value=selected[key];return}selected[key]=n;rebuild(selected)};
function syncAngle(){if(!selected)return;const angle=((Math.round(selected.r*180/Math.PI)%360)+360)%360;$('angleNumber').value=angle;$('angleRange').value=angle;}
function setAngle(degrees){if(!selected||!Number.isFinite(degrees))return;selected.r=((degrees%360)+360)%360*Math.PI/180;selected.mesh.rotation.y=selected.r;selectionBox?.update();syncAngle();}
$('angleRange').oninput=e=>setAngle(Number(e.target.value));$('angleNumber').onchange=e=>setAngle(Number(e.target.value));
$('rotate').onclick=()=>selected&&setAngle(selected.r*180/Math.PI+90);$('rotateBack').onclick=()=>selected&&setAngle(selected.r*180/Math.PI-15);$('rotateSmall').onclick=()=>selected&&setAngle(selected.r*180/Math.PI+15);
$('furnitureName').onchange=e=>{if(selected){selected.name=e.target.value.trim()||presets[selected.type].name;$('selectedName').textContent=selected.name;renderList()}};
$('deselect').onclick=()=>select(null);
function removeItem(o){if(!o)return;disposeItem(o);furniture.splice(furniture.indexOf(o),1);if(selected===o)select(null);else renderList();$('status').textContent='가구를 삭제했어요. 저장 버튼을 누르면 저장 배치에도 반영됩니다.';}
$('delete').onclick=()=>removeItem(selected);
function renderList(){$('furnitureList').replaceChildren();$('objectCount').textContent=`${furniture.length} objects`;for(const o of furniture){const row=document.createElement('div');row.className='furnitureRow';const btn=document.createElement('button');btn.className=o===selected?'active':'';if(o.photo){const img=document.createElement('img');img.src=o.photo;img.alt='';btn.append(img)}btn.append(document.createTextNode(o.name));btn.onclick=()=>select(o);const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label',o.name+' 삭제');del.onclick=()=>removeItem(o);row.append(btn,del);$('furnitureList').append(row)}}
window.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.activeElement.isContentEditable){e.preventDefault();removeItem(selected)}});
$('photoUpload').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('사진은 20MB 이하로 선택해주세요.');$('status').textContent='사진을 입체 모형에 적용하고 있어요…';const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,768/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let sum=[0,0,0],count=0;for(let i=0;i<data.length;i+=64){if(data[i]<235||data[i+1]<235||data[i+2]<235){sum[0]+=data[i];sum[1]+=data[i+1];sum[2]+=data[i+2];count++}}const color=count?(Math.round(sum[0]/count)<<16)|(Math.round(sum[1]/count)<<8)|Math.round(sum[2]/count):0xb5b0a4;const o={...presets.photo,type:'photo',name:file.name.replace(/\.[^.]+$/,'').slice(0,60)||'사진 가구',photo:canvas.toDataURL('image/webp',.85),color,x:L(2.5,5)[0],z:L(2.5,5)[1],r:0};furniture.push(o);rebuild(o);select(o);$('editor').scrollIntoView({block:'nearest',behavior:'smooth'});$('status').textContent='사진 가구를 추가했어요. 실제 가로·깊이·높이를 입력해주세요.';}catch(err){$('status').textContent=err.message.startsWith('사진은')?err.message:'사진을 읽지 못했어요. JPG·PNG·WebP 파일로 다시 선택해주세요.';}finally{e.target.value=''}};
$('lift').onchange=e=>{if(selected){selected.lift=Math.max(0,Math.min(3000,Number(e.target.value)||0));selected.mesh.position.y=selected.lift/1000;selectionBox?.update()}};
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);let dragging=false,offset=new THREE.Vector3();
function setRay(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera)}
renderer.domElement.addEventListener('pointerdown',e=>{if(walkMode){if(e.pointerType!=='mouse')lookTouch={id:e.pointerId,x:e.clientX,y:e.clientY};else if(document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock?.();return}setRay(e);const hits=ray.intersectObjects(furniture.map(o=>o.mesh),true);if(hits.length){let m=hits[0].object;while(!m.userData.item&&m.parent)m=m.parent;select(m.userData.item);const p=new THREE.Vector3();if(ray.ray.intersectPlane(ground,p)){offset.copy(selected.mesh.position).sub(p);dragging=true;controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId)}}},true);
renderer.domElement.addEventListener('pointermove',e=>{if(walkMode&&lookTouch?.id===e.pointerId){walkYaw-=(e.clientX-lookTouch.x)*.006;walkPitch=Math.max(-1.35,Math.min(1.35,walkPitch-(e.clientY-lookTouch.y)*.006));lookTouch.x=e.clientX;lookTouch.y=e.clientY;lookForward();return}if(!dragging||!selected)return;setRay(e);const p=new THREE.Vector3();if(ray.ray.intersectPlane(ground,p)){p.add(offset);const px=p.x,py=p.z;if(inside(px,py)){selected.x=p.x;selected.z=p.z;selected.mesh.position.set(p.x,(selected.lift||0)/1000,p.z);selectionBox?.update()}}});function endDrag(e){if(lookTouch?.id===e.pointerId)lookTouch=null;dragging=false;if(!walkMode)controls.enabled=true}renderer.domElement.addEventListener('pointerup',endDrag);renderer.domElement.addEventListener('pointercancel',endDrag);
const storage=document.querySelector('.storage');storage.innerHTML='<label class="slotLabel">저장 슬롯 <select id="layoutSlot"><option value="1">배치 1</option><option value="2">배치 2</option><option value="3">배치 3</option></select></label><div class="row"><button id="save">저장</button><button id="restore">불러오기</button></div><button id="shareLayout">현재 배치 링크 복사</button>';
function layoutData(){return furniture.map(({mesh,...o})=>o)}function validLayout(data){return Array.isArray(data)&&!data.some(o=>!presets[o.type]||!['w','d','h','x','z','r'].every(k=>Number.isFinite(o[k]))||o.w<5||o.w>8000||o.d<5||o.d>8000||o.h<5||o.h>3000||(o.type==='photo'&&!(typeof o.photo==='string'&&/^data:image\/(webp|png|jpeg);base64,/.test(o.photo))))}function loadLayout(data,message='배치를 불러왔어요.'){if(!validLayout(data))throw Error();select(null);furniture.forEach(disposeItem);furniture.length=0;data.forEach(o=>{furniture.push(o);rebuild(o)});renderList();$('status').textContent=message}function encodeLayout(data){const bytes=new TextEncoder().encode(JSON.stringify(data));let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}function decodeLayout(value){value=value.replaceAll('-','+').replaceAll('_','/');while(value.length%4)value+='=';const s=atob(value),bytes=Uint8Array.from(s,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
$('save').onclick=()=>{try{const slot=$('layoutSlot').value;localStorage.setItem('house-study-layout-'+slot,JSON.stringify(layoutData()));$('status').textContent='배치 '+slot+'에 저장했어요.'}catch{$('status').textContent='저장하지 못했어요. 사진 수를 줄이거나 브라우저 저장 공간을 확인해주세요.'}};
$('restore').onclick=()=>{try{const slot=$('layoutSlot').value,raw=localStorage.getItem('house-study-layout-'+slot);if(!raw){$('status').textContent='배치 '+slot+'에 저장된 내용이 없어요.';return}loadLayout(JSON.parse(raw),'배치 '+slot+'을 불러왔어요.')}catch{$('status').textContent='저장된 배치를 불러오지 못했어요.'}};
$('shareLayout').onclick=async()=>{try{const data=layoutData(),json=JSON.stringify(data);if(json.length>70000)throw Error('사진 가구가 포함된 큰 배치는 링크로 공유하기 어려워요.');const url=location.origin+location.pathname+'#layout='+encodeLayout(data);history.replaceState(null,'',url);await navigator.clipboard.writeText(url);$('status').textContent='현재 배치 공유 링크를 복사했어요. 다른 기기에서도 같은 배치가 열립니다.'}catch(err){$('status').textContent=err.message||'공유 링크를 만들지 못했어요.'}};
$('reference').onclick=()=>$('referenceDialog').showModal();$('closeReference').onclick=()=>$('referenceDialog').close();
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();view('overview');$('loading').remove();
function animate(){requestAnimationFrame(animate);const dt=Math.min(.05,walkClock.getDelta());if(walkMode){const f=new THREE.Vector3(-Math.sin(walkYaw),0,-Math.cos(walkYaw)),s=new THREE.Vector3(-f.z,0,f.x),move=new THREE.Vector3();if(walkKeys.has('KeyW')||walkKeys.has('ArrowUp'))move.add(f);if(walkKeys.has('KeyS')||walkKeys.has('ArrowDown'))move.sub(f);if(walkKeys.has('KeyA')||walkKeys.has('ArrowLeft'))move.sub(s);if(walkKeys.has('KeyD')||walkKeys.has('ArrowRight'))move.add(s);if(move.lengthSq()){move.normalize().multiplyScalar(2.25*dt);const next=camera.position.clone().add(move);walkRay.set(camera.position,move.clone().normalize());const blocked=walkRay.intersectObjects(walls,false).some(h=>h.distance<.38);if(inside(next.x,next.z)&&!blocked){camera.position.copy(next);camera.position.y=1.65}}lookForward()}else controls.update();for(const {el,p} of labels){const q=p.clone().project(camera);el.style.left=(q.x*.5+.5)*host.clientWidth+'px';el.style.top=(-q.y*.5+.5)*host.clientHeight+'px';el.style.display=q.z>1||q.z< -1?'none':''}renderer.render(scene,camera)}animate();

$('capture').onclick=()=>{select(null);const old=$('labels').hidden;$('labels').hidden=true;renderer.render(scene,camera);const a=document.createElement('a');a.download='room-render.png';a.href=renderer.domElement.toDataURL('image/png');a.click();$('labels').hidden=old;};
function sample(){select(null);furniture.forEach(disposeItem);furniture.length=0;const a=Math.atan2(205,323);function put(type,u,v,angle=0,extra={}){const [x,z]=L(u,v);const o={...presets[type],type,x,z,r:-a+angle,...extra};furniture.push(o);rebuild(o)}
put('slabTable',2.0,.3,Math.PI/2);for(const v of [-.25,.85]){put('standard',1.13,v,-Math.PI/2);put('standard',2.87,v,Math.PI/2)}
put('naturalRug',2.8,7.5,Math.PI/2);put('modularSofa',2.7,5.65,0);put('sofa',2.7,9.5,Math.PI,{name:'기존 맞은편 소파 · 크기 임시',w:2500,d:950});put('coffee',2.7,7.6,0);put('pkLounge',.65,7,-Math.PI/2);put('pkLounge',.65,8.15,-Math.PI/2);put('tv',5.0,7.55,Math.PI/2);for(const v of [6.4,8.7]){put('speakerStand',4.85,v,Math.PI/2);put('monitorSpeaker',4.85,v,Math.PI/2,{lift:600})}
put('woodLamp',1.0,10.25);put('woodLamp',1,-.75);put('paperPendant',2,.3);for(const v of [2.2,3.15])put('ropeBar',3, v,-Math.PI/2);put('cabinet',3.8,-.6,Math.PI,{w:1400});put('bed',7.375,8.6,Math.PI);put('woodChair',7.5,7.0);renderList();view('living');$('status').textContent='화면 참고 기본 배치입니다. 러그·받침대·기존 소파 등 미제공 치수는 임시값입니다. 저장 배치는 덮어쓰지 않았어요.';}
$('sampleLayout').onclick=()=>{if(furniture.length&&!confirm('현재 화면을 기본 배치로 바꿀까요? 저장된 배치는 유지됩니다.'))return;sample();};
try{if(location.hash.startsWith('#layout='))loadLayout(decodeLayout(location.hash.slice(8)),'공유된 배치를 불러왔어요.');else{const legacy=localStorage.getItem('house-study-layout-1')||localStorage.getItem('house-study-furniture-v2');if(legacy)loadLayout(JSON.parse(legacy),'배치 1을 불러왔어요.');else sample()}}catch{sample();$('status').textContent='공유 또는 저장 배치를 읽지 못해 기본 배치를 열었어요.'}

function setFurnitureColor(value){if(!selected||clientPresets[selected.type]||selected.type==='photo'||selected.type==='tv')return;selected.color=parseInt(value.slice(1),16);selected.colorOverride=true;$('fcolor').value=value;rebuild(selected);}
$('fcolor').oninput=e=>setFurnitureColor(e.target.value);
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>setFurnitureColor(b.dataset.color));
